version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb+srv://achrafthedev:hxWtyPZsQp6bFX6N@frontcluster.bhg4zjp.mongodb.net/" 
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-network

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - backend-network

networks:
  backend-network: